
# Configure this Discovery Server
eureka:
  instance:
    ip-address: 10.138.25.214
  client:
    serviceUrl:
      defaultZone: http://10.138.25.214:1111/eureka
  server:
    enable-self-preservation: false

server:
  port: 1111   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
  application:
    name: prod-eureka