
# Configure this Discovery Server
eureka:
  instance:
    ip-address: 10.138.25.211
  client:
    serviceUrl:
      defaultZone: http://10.138.25.211:1111/eureka
  server:
    enable-self-preservation: false

server:
  port: 1111   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false      # Disable Thymeleaf
  application:
    name: test-eureka